
GET http://localhost:3000/users

###


Get http://localhost:3000/users/5eb5a883d60eee02283e8613
###
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Ali",
  "lastName": "Kazmi",
  "birthday":"2001-01-16",
  "location": "California"
}

###
PATCH http://localhost:3000/users/5eb61e5e9c30f14563abe7d7
Content-Type: application/json 

{
  "currentResult":1
}

###
DELETE http://localhost:3000/users/5eba0b94c284772088412f7f



###
PATCH http://localhost:3000/users/5eb5a883d60eee02283e8613
Content-Type: application/json 

{
  "firstName": "Tommy"
}